<?php
$permission['dashboard.php']='can_view_dashboard';
$permission['view_employee_list.php']='can_view_employee_list';
$permission['view_employee.php']='can_view_employee';
$permission['create_employee.php']='can_create_employee';
$permission['edit_employee.php']='can_edit_employee';
$permission['delete_employee.php']='can_delete_employee';
$permission['view_customer_list.php']='can_view_customer_list';
$permission['view_customers.php']='can_view_customer';
$permission['create_customer.php']='can_create_customer';
$permission['edit_customers.php']='can_edit_customer';
$permission['delete_customers.php']='can_delete_customer';
$permission['view_project_list.php']='can_view_project_list';
$permission['view_project.php']='can_view_projects';
$permission['manage_task.php']='can_view_projects';
$permission['create_project.php']='can_create_projects';
$permission['edit_project.php']='can_edit_projects';
$permission['delete_project.php']='can_delete_projects';
$permission['manage_task.php']='can_view_projects';
$permission['view_task_list.php']='can_view_projects';
?>